### ISSUE TITLE
Do we need this repo?

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/admin#14] opened 2019-05-06 16:17 UTC
Thinking about this again i'm not 100% we need this repo. As we only have a single Council (CPC) it may make sense to just keep everything in a single place. Let's discuss later today

**Comment by obensource** [comment] 2019-05-06 18:45
After discussing #14, the bootstrap team determined in [today's meeting](https://github.com/openjs-foundation/bootstrap/issues/168) that the [admin](https://github.com/openjs-foundation/admin) repository isn't relevant at this time as we only have one Top Level Committee and we'll be renaming the bootstrap repo to `cross-project-council` soon – which will handle any concerns the admin repo was intended to address.

I'll be deleting this repo and migrating any relevant issues to the [/bootstrap](https://github.com/openjs-foundation/bootstrap) repository.

Given the above, I'm closing this issue. 👍

**Closed by obensource** 2019-05-06 18:45 UTC
